`timescale 1ns / 1ps

module conv3x3_four_lane_parallel (
    input  wire                    clk,
    input  wire                    reset,
    input  wire                    input_valid,
    input  wire signed [7:0]       input_value_0,
    input  wire signed [7:0]       input_value_1,
    input  wire signed [7:0]       input_value_2,
    input  wire signed [7:0]       input_value_3,
    input  wire signed [7:0]       input_value_4,
    input  wire signed [7:0]       input_value_5,
    input  wire signed [7:0]       input_value_6,
    input  wire signed [7:0]       input_value_7,
    input  wire signed [7:0]       input_value_8,
    input  wire signed [7:0]       weight_lane_0_value_0,
    input  wire signed [7:0]       weight_lane_0_value_1,
    input  wire signed [7:0]       weight_lane_0_value_2,
    input  wire signed [7:0]       weight_lane_0_value_3,
    input  wire signed [7:0]       weight_lane_0_value_4,
    input  wire signed [7:0]       weight_lane_0_value_5,
    input  wire signed [7:0]       weight_lane_0_value_6,
    input  wire signed [7:0]       weight_lane_0_value_7,
    input  wire signed [7:0]       weight_lane_0_value_8,
    input  wire signed [7:0]       weight_lane_1_value_0,
    input  wire signed [7:0]       weight_lane_1_value_1,
    input  wire signed [7:0]       weight_lane_1_value_2,
    input  wire signed [7:0]       weight_lane_1_value_3,
    input  wire signed [7:0]       weight_lane_1_value_4,
    input  wire signed [7:0]       weight_lane_1_value_5,
    input  wire signed [7:0]       weight_lane_1_value_6,
    input  wire signed [7:0]       weight_lane_1_value_7,
    input  wire signed [7:0]       weight_lane_1_value_8,
    input  wire signed [7:0]       weight_lane_2_value_0,
    input  wire signed [7:0]       weight_lane_2_value_1,
    input  wire signed [7:0]       weight_lane_2_value_2,
    input  wire signed [7:0]       weight_lane_2_value_3,
    input  wire signed [7:0]       weight_lane_2_value_4,
    input  wire signed [7:0]       weight_lane_2_value_5,
    input  wire signed [7:0]       weight_lane_2_value_6,
    input  wire signed [7:0]       weight_lane_2_value_7,
    input  wire signed [7:0]       weight_lane_2_value_8,
    input  wire signed [7:0]       weight_lane_3_value_0,
    input  wire signed [7:0]       weight_lane_3_value_1,
    input  wire signed [7:0]       weight_lane_3_value_2,
    input  wire signed [7:0]       weight_lane_3_value_3,
    input  wire signed [7:0]       weight_lane_3_value_4,
    input  wire signed [7:0]       weight_lane_3_value_5,
    input  wire signed [7:0]       weight_lane_3_value_6,
    input  wire signed [7:0]       weight_lane_3_value_7,
    input  wire signed [7:0]       weight_lane_3_value_8,
    output wire signed [63:0]      partial_sum_0,
    output wire signed [63:0]      partial_sum_1,
    output wire signed [63:0]      partial_sum_2,
    output wire signed [63:0]      partial_sum_3,
    output wire                    partial_sum_valid
);
    wire partial_sum_valid_0;
    wire partial_sum_valid_1;
    wire partial_sum_valid_2;
    wire partial_sum_valid_3;
    initial begin
        $display("ACTIVE RTL: conv3x3_four_lane_parallel FOUR-LANE NINE-TAP V1");
    end
    assign partial_sum_valid =
        partial_sum_valid_0 &&
        partial_sum_valid_1 &&
        partial_sum_valid_2 &&
        partial_sum_valid_3;
    // Four output lanes share the same 3x3 activation window.
    conv3x3_parallel_dot_product lane_0_inst (
        .clk(clk),
        .rst(reset),
        .input_valid(input_valid),
        .input_value_0(input_value_0),
        .input_value_1(input_value_1),
        .input_value_2(input_value_2),
        .input_value_3(input_value_3),
        .input_value_4(input_value_4),
        .input_value_5(input_value_5),
        .input_value_6(input_value_6),
        .input_value_7(input_value_7),
        .input_value_8(input_value_8),
        .weight_value_0(weight_lane_0_value_0),
        .weight_value_1(weight_lane_0_value_1),
        .weight_value_2(weight_lane_0_value_2),
        .weight_value_3(weight_lane_0_value_3),
        .weight_value_4(weight_lane_0_value_4),
        .weight_value_5(weight_lane_0_value_5),
        .weight_value_6(weight_lane_0_value_6),
        .weight_value_7(weight_lane_0_value_7),
        .weight_value_8(weight_lane_0_value_8),
        .partial_sum(partial_sum_0),
        .partial_sum_valid(partial_sum_valid_0)
    );
    conv3x3_parallel_dot_product lane_1_inst (
        .clk(clk),
        .rst(reset),
        .input_valid(input_valid),
        .input_value_0(input_value_0),
        .input_value_1(input_value_1),
        .input_value_2(input_value_2),
        .input_value_3(input_value_3),
        .input_value_4(input_value_4),
        .input_value_5(input_value_5),
        .input_value_6(input_value_6),
        .input_value_7(input_value_7),
        .input_value_8(input_value_8),
        .weight_value_0(weight_lane_1_value_0),
        .weight_value_1(weight_lane_1_value_1),
        .weight_value_2(weight_lane_1_value_2),
        .weight_value_3(weight_lane_1_value_3),
        .weight_value_4(weight_lane_1_value_4),
        .weight_value_5(weight_lane_1_value_5),
        .weight_value_6(weight_lane_1_value_6),
        .weight_value_7(weight_lane_1_value_7),
        .weight_value_8(weight_lane_1_value_8),
        .partial_sum(partial_sum_1),
        .partial_sum_valid(partial_sum_valid_1)
    );
    conv3x3_parallel_dot_product lane_2_inst (
        .clk(clk),
        .rst(reset),
        .input_valid(input_valid),
        .input_value_0(input_value_0),
        .input_value_1(input_value_1),
        .input_value_2(input_value_2),
        .input_value_3(input_value_3),
        .input_value_4(input_value_4),
        .input_value_5(input_value_5),
        .input_value_6(input_value_6),
        .input_value_7(input_value_7),
        .input_value_8(input_value_8),
        .weight_value_0(weight_lane_2_value_0),
        .weight_value_1(weight_lane_2_value_1),
        .weight_value_2(weight_lane_2_value_2),
        .weight_value_3(weight_lane_2_value_3),
        .weight_value_4(weight_lane_2_value_4),
        .weight_value_5(weight_lane_2_value_5),
        .weight_value_6(weight_lane_2_value_6),
        .weight_value_7(weight_lane_2_value_7),
        .weight_value_8(weight_lane_2_value_8),
        .partial_sum(partial_sum_2),
        .partial_sum_valid(partial_sum_valid_2)
    );
    conv3x3_parallel_dot_product lane_3_inst (
        .clk(clk),
        .rst(reset),
        .input_valid(input_valid),
        .input_value_0(input_value_0),
        .input_value_1(input_value_1),
        .input_value_2(input_value_2),
        .input_value_3(input_value_3),
        .input_value_4(input_value_4),
        .input_value_5(input_value_5),
        .input_value_6(input_value_6),
        .input_value_7(input_value_7),
        .input_value_8(input_value_8),
        .weight_value_0(weight_lane_3_value_0),
        .weight_value_1(weight_lane_3_value_1),
        .weight_value_2(weight_lane_3_value_2),
        .weight_value_3(weight_lane_3_value_3),
        .weight_value_4(weight_lane_3_value_4),
        .weight_value_5(weight_lane_3_value_5),
        .weight_value_6(weight_lane_3_value_6),
        .weight_value_7(weight_lane_3_value_7),
        .weight_value_8(weight_lane_3_value_8),
        .partial_sum(partial_sum_3),
        .partial_sum_valid(partial_sum_valid_3)
    );
endmodule
